const initialUsersArray = [
  {
    firstName: "Albin",
    lastName: "Pierre",
    email: "albin.pierre@gmail.com",
    password: "password123",
    profilePicture: "profile1.jpg",
    bio: "Software engineer with a passion for frontend development.",
    github: "albinpierre",
    linkedin: "albinpierre",
    school: "Massachusetts Institute of Technology (MIT)",
  },
  {
    firstName: "Alden",
    lastName: "Hale",
    email: "alden.hale@yahoo.com",
    password: "password456",
    profilePicture: "profile2.jpg",
    bio: "Full-stack developer experienced in building scalable web applications.",
    github: "aldenhale",
    linkedin: "aldenhale",
    school: "Stanford University",
  },
  {
    firstName: "Cade",
    lastName: "Weldon",
    email: "cade.weldon@hotmail.com",
    password: "password789",
    profilePicture: "profile3.jpg",
    bio: "Backend developer specialized in database management and optimization.",
    github: "cadeweldon",
    linkedin: "cadeweldon",
    school: "University of California, Berkeley",
  },
  {
    firstName: "Daxton",
    lastName: "Indiana",
    email: "daxton.indiana@outlook.com",
    password: "passwordabc",
    profilePicture: "profile4.jpg",
    bio: "DevOps engineer focused on automating development and deployment processes.",
    github: "daxtonindiana",
    linkedin: "daxtonindiana",
    school: "Carnegie Mellon University",
  },
  {
    firstName: "Hudson",
    lastName: "Jaron",
    email: "hudson.jaron@gmail.com",
    password: "passworddef",
    profilePicture: "profile5.jpg",
    bio: "Frontend developer with expertise in building responsive user interfaces.",
    github: "hudsonjaron",
    linkedin: "hudsonjaron",
    school: "University of Illinois at Urbana-Champaign",
  },
  {
    firstName: "Jez",
    lastName: "Jerald",
    email: "jez.jerald@yahoo.com",
    password: "passwordghi",
    profilePicture: "profile6.jpg",
    bio: "Mobile app developer specializing in iOS and Android platforms.",
    github: "jezjerald",
    linkedin: "jezjerald",
    school: "Harvard University",
  },
  {
    firstName: "Joanna",
    lastName: "Noelene",
    email: "joanna.noelene@gmail.com",
    password: "passwordjkl",
    profilePicture: "profile7.jpg",
    bio: "Experienced software architect passionate about designing scalable and robust systems.",
    github: "joannoel",
    linkedin: "joannoelene",
    school: "California Institute of Technology (Caltech)",
  },
  {
    firstName: "Laurencia",
    lastName: "Felicity",
    email: "laurencia.felicity@yahoo.com",
    password: "passwordmno",
    profilePicture: "profile8.jpg",
    bio: "Data scientist with expertise in machine learning and data analytics.",
    github: "laurenciafelicity",
    linkedin: "laurenciafelicity",
    school: "University of Cambridge",
  },
  {
    firstName: "Lora",
    lastName: "Gertie",
    email: "lora.gertie@gmail.com",
    password: "password123",
    profilePicture: "profile9.jpg",
    bio: "Frontend developer passionate about creating elegant and intuitive user interfaces.",
    github: "loragertie",
    linkedin: "loragertie",
    school: "University of Texas at Austin",
  },
  {
    firstName: "Mack",
    lastName: "Casimir",
    email: "mack.casimir@yahoo.com",
    password: "password456",
    profilePicture: "profile10.jpg",
    bio: "Experienced backend developer specializing in server-side technologies.",
    github: "mackcasimir",
    linkedin: "mackcasimir",
    school: "University of Washington",
  },
  {
    firstName: "Marissa",
    lastName: "Deonne",
    email: "marissa.deonne@hotmail.com",
    password: "password789",
    profilePicture: "profile11.jpg",
    bio: "UI/UX designer with a focus on creating visually appealing and user-friendly interfaces.",
    github: "marissadeonne",
    linkedin: "marissadeonne",
    school: "Rhode Island School of Design (RISD)",
  },
  {
    firstName: "Ned",
    lastName: "Thorburn",
    email: "ned.thorburn@outlook.com",
    password: "passwordabc",
    profilePicture: "profile12.jpg",
    bio: "Software engineer with expertise in building scalable and distributed systems.",
    github: "nedthorburn",
    linkedin: "nedthorburn",
    school: "Georgia Institute of Technology (Georgia Tech)",
  },
  {
    firstName: "Petunia",
    lastName: "Ariel",
    email: "petunia.ariel@gmail.com",
    password: "passworddef",
    profilePicture: "profile13.jpg",
    bio: "AI enthusiast and machine learning engineer passionate about pushing the boundaries of technology.",
    github: "petuniaariel",
    linkedin: "petuniaariel",
    school: "University of California, Los Angeles (UCLA)",
  },
  {
    firstName: "Rex",
    lastName: "Benton",
    email: "rex.benton@yahoo.com",
    password: "passwordghi",
    profilePicture: "profile14.jpg",
    bio: "Full-stack developer with a knack for problem-solving and building robust applications.",
    github: "rexbenton",
    linkedin: "rexbenton",
    school: "University of Michigan",
  },
  {
    firstName: "Roscoe",
    lastName: "Kendall",
    email: "roscoe.kendall@hotmail.com",
    password: "passwordjkl",
    profilePicture: "profile15.jpg",
    bio: "Passionate software engineer dedicated to creating efficient and maintainable code.",
    github: "roscoekendall",
    linkedin: "roscoekendall",
    school: "University of California, San Diego (UCSD)",
  },
  {
    firstName: "Seth",
    lastName: "Silas",
    email: "seth.silas@gmail.com",
    password: "password123",
    profilePicture: "profile17.jpg",
    bio: "Experienced mobile app developer specializing in cross-platform development.",
    github: "sethsilas",
    linkedin: "sethsilas",
    school: "University of California, Santa Barbara (UCSB)",
  },
  {
    firstName: "Shuan",
    lastName: "Aydan",
    email: "shuan.aydan@yahoo.com",
    password: "password456",
    profilePicture: "profile18.jpg",
    bio: "Software engineer with a keen interest in artificial intelligence and data science.",
    github: "shuanaydan",
    linkedin: "shuanaydan",
    school: "University of Waterloo",
  },
  {
    firstName: "Shayne",
    lastName: "Cambell",
    email: "shayne.cambell@hotmail.com",
    password: "password789",
    profilePicture: "profile19.jpg",
    bio: "Frontend developer with a passion for creating visually stunning web interfaces.",
    github: "shaynecambell",
    linkedin: "shaynecambell",
    school: "University of California, Irvine (UCI)",
  },
  {
    firstName: "Steve",
    lastName: "Roman",
    email: "steve.roman@gmail.com",
    password: "passwordabc",
    profilePicture: "profile20.jpg",
    bio: "Full-stack developer experienced in building scalable and high-performance applications.",
    github: "steveroman",
    linkedin: "steveroman",
    school: "University of Toronto",
  },
  {
    firstName: "Sydney",
    lastName: "Virgee",
    email: "sydney.virgee@yahoo.com",
    password: "passworddef",
    profilePicture: "profile21.jpg",
    bio: "Passionate software engineer with expertise in backend development and cloud computing.",
    github: "sydneyvirgee",
    linkedin: "sydneyvirgee",
    school: "University of British Columbia",
  },
  {
    firstName: "Tisha",
    lastName: "Lorri",
    email: "tisha.lorri@gmail.com",
    password: "passwordghi",
    profilePicture: "profile22.jpg",
    bio: "UI/UX designer specializing in creating intuitive and user-centered design solutions.",
    github: "tishalorri",
    linkedin: "tishalorri",
    school: "New York University (NYU)",
  },
  {
    firstName: "Toni",
    lastName: "Isbel",
    email: "toni.isbel@yahoo.com",
    password: "passwordjkl",
    profilePicture: "profile23.jpg",
    bio: "Experienced data analyst with a passion for extracting insights from complex datasets.",
    github: "toniisbel",
    linkedin: "toniisbel",
    school: "University of Pennsylvania",
  },
  {
    firstName: "Tyson",
    lastName: "Bryant",
    email: "tyson.bryant@gmail.com",
    password: "passwordmno",
    profilePicture: "profile24.jpg",
    bio: "Backend developer with expertise in building scalable and secure server-side applications.",
    github: "tysonbryant",
    linkedin: "tysonbryant",
    school: "University of Chicago",
  },
];

module.exports = initialUsersArray;
